// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string achievement_feeling_the_speed = "CgkIg8bttbYQEAIQBw"; // <GPGSID>
        public const string achievement_50000_km = "CgkIg8bttbYQEAIQAw"; // <GPGSID>
        public const string achievement_1000000_km = "CgkIg8bttbYQEAIQBg"; // <GPGSID>
        public const string achievement_login = "CgkIg8bttbYQEAIQAg"; // <GPGSID>
        public const string achievement_take_it_up_a_notch = "CgkIg8bttbYQEAIQCA"; // <GPGSID>
        public const string achievement_keeping_it_hot = "CgkIg8bttbYQEAIQBQ"; // <GPGSID>
        public const string leaderboard_high_score = "CgkIg8bttbYQEAIQAQ"; // <GPGSID>
        public const string achievement_100000_km = "CgkIg8bttbYQEAIQBA"; // <GPGSID>

}

